version: '3.8'

services:
  libraryit-server:
    build: .
    container_name: libraryit-server
    ports:
      - "1445:445"
    volumes:
      - ./data:/libraryit
      - ./logs:/var/log/samba
    restart: always

  libraryit-logger:
    image: busybox
    container_name: libraryit-logger
    depends_on:
      - libraryit-server
    volumes:
      - ./logs:/var/log/samba # Samakan dengan server biar ga pusing
    #tail -F (F besar) supaya kalau file log sempat terhapus/rotate, dia otomatis nge-track lagi
    command: tail -F /var/log/samba/libraryit.log
