[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = bad user
   
   # Logging Utama
   log file = /var/log/samba/libraryit.log
   max log size = 50
   log level = 0 vfs:1

   # Supaya log bersih dari header debug (Poin d)
   debug prefix timestamp = no

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   read only = no
   valid users = @readonly @staff
   write list = @staff
   # Audit Module
   vfs objects = full_audit
   full_audit:prefix = [%t] [INFO] [%u] [%a] [%S]
   full_audit:success = connect disconnect openat mkdirat renameat unlinkat pwrite
   full_audit:failure = connect openat
   full_audit:syslog = no

[papers]
   path = /libraryit/papers
   browseable = yes
   read only = no
   valid users = @readonly @staff
   write list = @staff
   vfs objects = full_audit
   full_audit:prefix = [%t] [INFO] [%u] [%a] [%S]
   full_audit:success = connect disconnect openat mkdirat renameat unlinkat pwrite
   full_audit:failure = connect openat
   full_audit:syslog = no

[sourcecode]
   path = /libraryit/sourcecode
   browseable = no
   valid users = @staff
   write list = @staff
   vfs objects = full_audit
   full_audit:prefix = [%t] [INFO] [%u] [%a] [%S]
   full_audit:success = connect disconnect openat mkdirat renameat unlinkat pwrite
   full_audit:failure = connect openat
   full_audit:syslog = no

[docs]
   path = /libraryit/docs
   browseable = yes
   read only = yes
   valid users = @readonly @staff
   write list = librarian
   vfs objects = full_audit
   full_audit:prefix = [%t] [INFO] [%u] [%a] [%S]
   full_audit:success = connect disconnect openat mkdirat renameat unlinkat pwrite
   full_audit:failure = connect openat
   full_audit:syslog = no
